; generated by PrusaSlicer 2.2.0+win64 on 2020-07-17 at 19:29:03 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E1.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q5 S1
M73 P5 R1
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.06 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X125.000 Y101.737
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F900
G1 X128.173 Y101.737 E0.09948
G1 X128.173 Y107.543 E0.18203
G1 X121.827 Y107.543 E0.19897
G1 X121.827 Y101.737 E0.18203
G1 X124.940 Y101.737 E0.09760
G1 E-0.80000 F2100.00000
G1 Z0.800 F10800.000
G1 X125.000 Y107.920
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F900
G1 X121.450 Y107.920 E0.11131
G1 X121.450 Y101.360 E0.20568
G1 X128.550 Y101.360 E0.22262
G1 X128.550 Y107.920 E0.20568
G1 X125.060 Y107.920 E0.10943
G1 X124.691 Y107.665 F10800.000
G1 E-0.80000 F2100.00000
G1 Z0.800 F10800.000
G1 X128.060 Y102.615
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F900
G1 X127.464 Y102.020 E0.02650
G1 X126.929 Y102.020 E0.01684
G1 X127.890 Y102.981 E0.04277
G1 X127.890 Y103.516 E0.01684
G1 X126.394 Y102.020 E0.06658
G1 X125.859 Y102.020 E0.01684
G1 X127.890 Y104.051 E0.09040
G1 X127.890 Y104.586 E0.01684
G1 X125.324 Y102.020 E0.11422
G1 X124.788 Y102.020 E0.01684
G1 X127.890 Y105.122 E0.13804
G1 X127.890 Y105.657 E0.01684
G1 X124.253 Y102.020 E0.16186
G1 X123.718 Y102.020 E0.01684
G1 X127.890 Y106.192 E0.18567
G1 X127.890 Y106.727 E0.01684
G1 X123.183 Y102.020 E0.20949
G1 X122.648 Y102.020 E0.01684
G1 X127.888 Y107.260 E0.23319
G1 X127.352 Y107.260 E0.01684
G1 X122.110 Y102.020 E0.23325
G1 X122.110 Y102.553 E0.01677
G1 X126.817 Y107.260 E0.20949
G1 X126.282 Y107.260 E0.01684
G1 X122.110 Y103.088 E0.18567
G1 X122.110 Y103.623 E0.01684
G1 X125.747 Y107.260 E0.16185
G1 X125.212 Y107.260 E0.01684
G1 X122.110 Y104.158 E0.13803
G1 X122.110 Y104.693 E0.01684
G1 X124.676 Y107.260 E0.11421
G1 X124.141 Y107.260 E0.01684
G1 X122.110 Y105.229 E0.09040
G1 X122.110 Y105.764 E0.01684
G1 X123.606 Y107.260 E0.06658
G1 X123.071 Y107.260 E0.01684
G1 X122.110 Y106.299 E0.04276
G1 X122.110 Y106.834 E0.01684
G1 X122.705 Y107.430 E0.02650
M106 S255
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


G1 E-0.80000 F2100.00000
G1 Z0.800 F10800.000
;AFTER_LAYER_CHANGE
;0.4
M104 S210 ; set temperature
G1 X125.000 Y107.638
G1 Z0.400
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X121.872 Y107.638 E0.10588
G1 X121.872 Y101.922 E0.19347
G1 X128.128 Y101.922 E0.21175
G1 X128.128 Y107.638 E0.19347
G1 X125.060 Y107.638 E0.10385
M204 S1000
G1 E-0.80000 F2100.00000
G1 Z1.000 F10800.000
G1 X121.465 Y101.515
G1 Z0.400
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X128.535 Y101.515 E0.23931
G1 X128.535 Y108.045 E0.22103
G1 X121.465 Y108.045 E0.23931
G1 X121.465 Y101.575 E0.21900
M204 S1000
G1 X121.853 Y101.613 F10800.000
G1 E-0.80000 F2100.00000
G1 Z1.000 F10800.000
G1 X127.179 Y107.516
G1 Z0.400
G1 E0.80000 F2100.00000
M204 S1250
G1 F900
G1 X127.823 Y106.872 E0.03094
G1 X127.823 Y106.294 E0.01966
G1 X126.784 Y107.332 E0.04993
G1 X126.206 Y107.332 E0.01966
G1 X127.823 Y105.716 E0.07773
G1 X127.823 Y105.137 E0.01966
G1 X125.628 Y107.332 E0.10553
G1 X125.049 Y107.332 E0.01966
G1 X127.823 Y104.559 E0.13333
G1 X127.823 Y103.981 E0.01966
G1 X124.471 Y107.332 E0.16114
G1 X123.893 Y107.332 E0.01966
G1 X127.823 Y103.403 E0.18894
G1 X127.823 Y102.825 E0.01966
G1 X123.315 Y107.332 E0.21674
G1 X122.737 Y107.332 E0.01966
G1 X127.823 Y102.246 E0.24454
G1 X127.823 Y102.227 E0.00064
G1 X127.263 Y102.227 E0.01901
G1 X122.177 Y107.313 E0.24453
G1 X122.177 Y106.735 E0.01966
G1 X126.685 Y102.227 E0.21673
G1 X126.107 Y102.227 E0.01966
G1 X122.177 Y106.157 E0.18893
G1 X122.177 Y105.579 E0.01966
G1 X125.529 Y102.227 E0.16113
G1 X124.950 Y102.227 E0.01966
G1 X122.177 Y105.000 E0.13333
G1 X122.177 Y104.422 E0.01966
G1 X124.372 Y102.227 E0.10553
G1 X123.794 Y102.227 E0.01966
G1 X122.177 Y103.844 E0.07773
G1 X122.177 Y103.266 E0.01966
G1 X123.216 Y102.227 E0.04993
G1 X122.638 Y102.227 E0.01966
G1 X121.994 Y102.871 E0.03093
M204 S1000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6


G1 E-0.80000 F2100.00000
G1 Z1.000 F10800.000
;AFTER_LAYER_CHANGE
;0.6
G1 X125.000 Y107.778
G1 Z0.600
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X121.872 Y107.778 E0.10588
G1 X121.872 Y102.062 E0.19347
G1 X128.128 Y102.062 E0.21175
G1 X128.128 Y107.778 E0.19347
G1 X125.060 Y107.778 E0.10385
M204 S1000
G1 E-0.80000 F2100.00000
G1 Z1.200 F10800.000
G1 X121.465 Y101.655
G1 Z0.600
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X128.535 Y101.655 E0.23931
G1 X128.535 Y108.185 E0.22103
G1 X121.465 Y108.185 E0.23931
G1 X121.465 Y101.715 E0.21900
M204 S1000
G1 X121.853 Y101.753 F10800.000
G1 E-0.80000 F2100.00000
G1 Z1.200 F10800.000
G1 X128.006 Y103.011
G1 Z0.600
G1 E0.80000 F2100.00000
M204 S1250
G1 F900
G1 X127.362 Y102.367 E0.03094
G1 X126.784 Y102.367 E0.01966
G1 X127.823 Y103.406 E0.04993
G1 X127.823 Y103.984 E0.01966
G1 X126.206 Y102.367 E0.07773
G1 X125.628 Y102.367 E0.01966
G1 X127.823 Y104.562 E0.10554
G1 X127.823 Y105.141 E0.01966
G1 X125.049 Y102.367 E0.13334
G1 X124.471 Y102.367 E0.01966
G1 X127.823 Y105.719 E0.16114
G1 X127.823 Y106.297 E0.01966
G1 X123.893 Y102.367 E0.18894
G1 X123.315 Y102.367 E0.01966
G1 X127.823 Y106.875 E0.21674
G1 X127.823 Y107.454 E0.01966
G1 X122.736 Y102.367 E0.24454
G1 X122.177 Y102.367 E0.01901
G1 X122.177 Y102.386 E0.00065
G1 X127.263 Y107.472 E0.24453
G1 X126.685 Y107.472 E0.01966
G1 X122.177 Y102.965 E0.21673
G1 X122.177 Y103.543 E0.01966
G1 X126.107 Y107.472 E0.18893
G1 X125.529 Y107.472 E0.01966
G1 X122.177 Y104.121 E0.16113
G1 X122.177 Y104.699 E0.01966
G1 X124.950 Y107.472 E0.13333
G1 X124.372 Y107.472 E0.01966
G1 X122.177 Y105.278 E0.10553
G1 X122.177 Y105.856 E0.01966
G1 X123.794 Y107.472 E0.07773
G1 X123.216 Y107.472 E0.01966
G1 X122.177 Y106.434 E0.04993
G1 X122.177 Y107.012 E0.01966
G1 X122.821 Y107.656 E0.03093
M204 S1000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


G1 E-0.80000 F2100.00000
G1 Z1.200 F10800.000
;AFTER_LAYER_CHANGE
;0.8
G1 X125.000 Y107.918
G1 Z0.800
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X121.872 Y107.918 E0.10588
G1 X121.872 Y102.202 E0.19347
G1 X128.128 Y102.202 E0.21175
G1 X128.128 Y107.918 E0.19347
G1 X125.060 Y107.918 E0.10385
M204 S1000
G1 E-0.80000 F2100.00000
G1 Z1.400 F10800.000
G1 X121.465 Y101.795
G1 Z0.800
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X128.535 Y101.795 E0.23931
G1 X128.535 Y108.325 E0.22103
G1 X121.465 Y108.325 E0.23931
G1 X121.465 Y101.855 E0.21900
M204 S1000
G1 X121.853 Y101.893 F10800.000
G1 E-0.80000 F2100.00000
G1 Z1.400 F10800.000
G1 X127.179 Y107.796
G1 Z0.800
G1 E0.80000 F2100.00000
M204 S1250
G1 F900
G1 X127.823 Y107.152 E0.03094
G1 X127.823 Y106.574 E0.01966
G1 X126.784 Y107.612 E0.04993
G1 X126.206 Y107.612 E0.01966
G1 X127.823 Y105.996 E0.07773
G1 X127.823 Y105.418 E0.01966
G1 X125.628 Y107.612 E0.10553
G1 X125.049 Y107.612 E0.01966
G1 X127.823 Y104.839 E0.13333
G1 X127.823 Y104.261 E0.01966
G1 X124.471 Y107.612 E0.16114
G1 X123.893 Y107.612 E0.01966
G1 X127.823 Y103.683 E0.18894
G1 X127.823 Y103.105 E0.01966
G1 X123.315 Y107.612 E0.21674
G1 X122.737 Y107.612 E0.01966
G1 X127.823 Y102.526 E0.24454
G1 X127.823 Y102.507 E0.00064
G1 X127.263 Y102.507 E0.01901
G1 X122.177 Y107.593 E0.24453
G1 X122.177 Y107.015 E0.01966
G1 X126.685 Y102.507 E0.21673
G1 X126.107 Y102.507 E0.01966
G1 X122.177 Y106.437 E0.18893
G1 X122.177 Y105.859 E0.01966
G1 X125.529 Y102.507 E0.16113
G1 X124.950 Y102.507 E0.01966
G1 X122.177 Y105.281 E0.13333
G1 X122.177 Y104.702 E0.01966
G1 X124.372 Y102.507 E0.10553
G1 X123.794 Y102.507 E0.01966
G1 X122.177 Y104.124 E0.07773
G1 X122.177 Y103.546 E0.01966
G1 X123.216 Y102.507 E0.04993
G1 X122.638 Y102.507 E0.01966
G1 X121.994 Y103.151 E0.03093
M204 S1000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1


G1 E-0.80000 F2100.00000
G1 Z1.400 F10800.000
;AFTER_LAYER_CHANGE
;1
G1 X125.000 Y108.058
G1 Z1.000
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X121.872 Y108.058 E0.10588
G1 X121.872 Y102.342 E0.19347
G1 X128.128 Y102.342 E0.21175
G1 X128.128 Y108.058 E0.19347
G1 X125.060 Y108.058 E0.10385
M204 S1000
G1 E-0.80000 F2100.00000
G1 Z1.600 F10800.000
G1 X121.465 Y101.935
G1 Z1.000
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X128.535 Y101.935 E0.23931
G1 X128.535 Y108.465 E0.22103
G1 X121.465 Y108.465 E0.23931
G1 X121.465 Y101.995 E0.21900
M204 S1000
G1 X121.853 Y102.033 F10800.000
G1 E-0.80000 F2100.00000
G1 Z1.600 F10800.000
G1 X128.006 Y103.291
G1 Z1.000
G1 E0.80000 F2100.00000
M204 S1250
G1 F900
G1 X127.362 Y102.647 E0.03094
G1 X126.784 Y102.647 E0.01966
G1 X127.823 Y103.686 E0.04993
G1 X127.823 Y104.264 E0.01966
G1 X126.206 Y102.647 E0.07773
G1 X125.628 Y102.647 E0.01966
G1 X127.823 Y104.842 E0.10553
G1 X127.823 Y105.421 E0.01966
G1 X125.049 Y102.647 E0.13333
G1 X124.471 Y102.647 E0.01966
G1 X127.823 Y105.999 E0.16114
G1 X127.823 Y106.577 E0.01966
G1 X123.893 Y102.647 E0.18894
G1 X123.315 Y102.647 E0.01966
G1 X127.823 Y107.155 E0.21674
G1 X127.823 Y107.734 E0.01966
G1 X122.737 Y102.647 E0.24454
G1 X122.177 Y102.647 E0.01901
G1 X122.177 Y102.667 E0.00065
G1 X127.263 Y107.753 E0.24453
G1 X126.685 Y107.753 E0.01966
G1 X122.177 Y103.245 E0.21673
G1 X122.177 Y103.823 E0.01966
G1 X126.107 Y107.753 E0.18893
G1 X125.529 Y107.753 E0.01966
G1 X122.177 Y104.401 E0.16113
G1 X122.177 Y104.979 E0.01966
G1 X124.950 Y107.753 E0.13333
G1 X124.372 Y107.753 E0.01966
G1 X122.177 Y105.558 E0.10553
G1 X122.177 Y106.136 E0.01966
G1 X123.794 Y107.753 E0.07773
G1 X123.216 Y107.753 E0.01966
G1 X122.177 Y106.714 E0.04993
G1 X122.177 Y107.292 E0.01966
G1 X122.821 Y107.936 E0.03093
M204 S1000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.2


G1 E-0.80000 F2100.00000
G1 Z1.600 F10800.000
;AFTER_LAYER_CHANGE
;1.2
G1 X125.000 Y108.198
G1 Z1.200
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X121.872 Y108.198 E0.10588
G1 X121.872 Y102.482 E0.19347
G1 X128.128 Y102.482 E0.21175
G1 X128.128 Y108.198 E0.19347
G1 X125.060 Y108.198 E0.10385
M204 S1000
G1 E-0.80000 F2100.00000
G1 Z1.800 F10800.000
G1 X121.465 Y102.075
G1 Z1.200
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X128.535 Y102.075 E0.23931
G1 X128.535 Y108.605 E0.22103
G1 X121.465 Y108.605 E0.23931
G1 X121.465 Y102.135 E0.21900
M204 S1000
G1 X121.853 Y102.174 F10800.000
G1 E-0.80000 F2100.00000
G1 Z1.800 F10800.000
G1 X127.255 Y108.078
G1 Z1.200
G1 E0.80000 F2100.00000
M204 S1250
G1 F900
G1 X127.848 Y107.486 E0.02588
G1 X127.848 Y106.960 E0.01625
G1 X126.890 Y107.918 E0.04184
G1 X126.365 Y107.918 E0.01625
G1 X127.848 Y106.435 E0.06481
G1 X127.848 Y105.909 E0.01625
G1 X125.839 Y107.918 E0.08779
G1 X125.314 Y107.918 E0.01625
G1 X127.848 Y105.383 E0.11076
G1 X127.848 Y104.858 E0.01625
G1 X124.788 Y107.918 E0.13374
M73 Q85 S0
G1 X124.262 Y107.918 E0.01625
G1 X127.848 Y104.332 E0.15671
G1 X127.848 Y103.806 E0.01625
M73 P86 R0
G1 X123.737 Y107.918 E0.17969
G1 X123.211 Y107.918 E0.01625
G1 X127.848 Y103.281 E0.20267
G1 X127.848 Y102.763 E0.01602
G1 X122.685 Y107.918 E0.22548
G1 X122.160 Y107.918 E0.01625
G1 X127.315 Y102.763 E0.22532
G1 X126.789 Y102.763 E0.01625
G1 X122.152 Y107.399 E0.20266
G1 X122.152 Y106.873 E0.01625
G1 X126.263 Y102.763 E0.17968
G1 X125.738 Y102.763 E0.01625
G1 X122.152 Y106.348 E0.15671
G1 X122.152 Y105.822 E0.01625
G1 X125.212 Y102.763 E0.13373
G1 X124.686 Y102.763 E0.01625
G1 X122.152 Y105.296 E0.11076
G1 X122.152 Y104.771 E0.01625
G1 X124.161 Y102.763 E0.08778
G1 X123.635 Y102.763 E0.01625
G1 X122.152 Y104.245 E0.06480
G1 X122.152 Y103.720 E0.01625
G1 X123.109 Y102.763 E0.04183
G1 X122.584 Y102.763 E0.01625
G1 X121.992 Y103.355 E0.02588
M204 S1000
G1 E-0.80000 F2100.00000
G1 Z1.800 F10800.000
M107
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z31.8 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 26.9
; filament used [cm3] = 0.1
; filament used [g] = 0.1
; filament cost = 0.0

; total filament used [g] = 0.1
; total filament cost = 0.0
; estimated printing time (normal mode) = 1m 14s
; estimated printing time (silent mode) = 1m 14s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 10%
; fill_pattern = cubic
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1250
; infill_every_layers = 2
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 1
; infill_overlap = 25%
; infill_speed = 200
; inherits_cummulative = ;;"Original Prusa i3 MK3S"
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 1.5,1.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 2
; post_process = 
; print_settings_id = MK3S - JV
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = MK3S - JV
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = rear
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.6}0.04{else}0.06{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 1
; support_material_angle = 45
; support_material_auto = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear-grid
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 0
; support_material_xy_spacing = 75%
; temperature = 210
; thin_walls = 1
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 50
; top_solid_layers = 4
; top_solid_min_thickness = 0
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
